//import * as fields_local_panel from  './fields_local_panel.js'
import * as fields_panel from  './fields_panel.js'
import * as html_panel from  './html_panel.js'
import * as table_panel from  './table_panel.js'
import * as iframe from  './iframe.js'
import * as html_content_panel from  './html_content_panel.js'
import * as form_panel from  './form_panel.js'
import * as pop_fields_panel from  './pop_fields_panel.js'
import * as table_setting from  './table_setting.js'
import * as grid_layout from  './grid_layout.js'
import * as chart from  './chart.js'
import * as charts_main from  './charts/main'

import  pop_progress from  './pop_progress.vue'
Vue.component('com-pop-progress',pop_progress)