# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(verbose_name='创建时间')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='等级')),
                ('message', models.TextField(blank=True, verbose_name='消息体')),
                ('path', models.CharField(blank=True, max_length=300, verbose_name='消息来源')),
                ('process', models.CharField(blank=True, max_length=100, verbose_name='进程ID')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='主机名')),
            ],
        ),
        migrations.AddIndex(
            model_name='generallog',
            index=models.Index(fields=['createtime'], name='act_log_gen_createt_25a2bd_idx'),
        ),
    ]
