# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(verbose_name='创建时间')),
                ('table', models.CharField(blank=True, max_length=100, verbose_name='相关表')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('createuser', models.CharField(blank=True, max_length=100, verbose_name='操作人')),
            ],
        ),
        migrations.AddIndex(
            model_name='backendoperation',
            index=models.Index(fields=['createtime'], name='act_log_bac_createt_b2d166_idx'),
        ),
    ]
