# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-11 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('act_log', '0002_auto_20200811_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backendoperation',
            old_name='table',
            new_name='model',
        ),
    ]
