# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-10-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_log', '0003_auto_20200811_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendoperation',
            name='inst_pk',
            field=models.IntegerField(blank=True, null=True, verbose_name='主键'),
        ),
        migrations.AddField(
            model_name='backendoperation',
            name='op',
            field=models.CharField(blank=True, max_length=50, verbose_name='操作'),
        ),
    ]
