# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-10-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_log', '0004_auto_20201021_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendoperation',
            name='inst_pk',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='主键'),
            preserve_default=False,
        ),
    ]
