# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_log', '0005_auto_20201021_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='消息内容')),
                ('read', models.BooleanField(default=False, verbose_name='是否查看')),
                ('level', models.IntegerField(choices=[(10, '普通'), (20, '紧急'), (30, '关键')], verbose_name='等级')),
                ('createtime', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
    ]
