# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_log', '0006_systemmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendoperation',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='systemmessage',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
