# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='标识名')),
                ('label', models.CharField(max_length=200, verbose_name='标签名')),
                ('temp_cls', models.CharField(max_length=200, verbose_name='模板')),
                ('enable', models.BooleanField(default=True, verbose_name='启用')),
                ('detail', models.TextField(blank=True, verbose_name='描述')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simcms.CmsPageModel', verbose_name='继承')),
            ],
        ),
    ]
