# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspagemodel',
            name='label',
            field=models.CharField(help_text='便于人读的页面名称', max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='cmspagemodel',
            name='name',
            field=models.CharField(help_text='页面标识（唯一），用作页面url路径', max_length=60, unique=True, verbose_name='url'),
        ),
    ]
