# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-09 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_editor', '0002_page_desp'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, default='[]', verbose_name='内容'),
        ),
    ]
