# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-09 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_editor', '0003_auto_20220609_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='kind',
            field=models.IntegerField(choices=[(1, '普通组件'), (2, 'slot组件')], default=1, verbose_name='类型'),
        ),
    ]
