# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('director', '0002_kvmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitmodel',
            name='desp',
        ),
        migrations.RemoveField(
            model_name='permitmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='permitmodel',
            name='permit',
        ),
        migrations.AddField(
            model_name='permitmodel',
            name='names',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='permitmodel',
            name='group',
        ),
        migrations.AddField(
            model_name='permitmodel',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
