# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-16 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0009_auto_20170315_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='\u8be6\u7ec6'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='kind',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7c7b\u522b'),
        ),
    ]
