# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0010_auto_20170316_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='\u7ec6\u8282'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='kind',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u79cd\u7c7b'),
        ),
    ]
