# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0011_auto_20170411_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='kind',
            field=models.CharField(blank=True, max_length=100, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='permitmodel',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='user group'),
        ),
        migrations.AlterField(
            model_name='permitmodel',
            name='permit',
            field=models.TextField(default='{}', verbose_name='user permit'),
        ),
    ]
