# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-20 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0011_auto_20190320_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvmodel',
            name='editor_type',
        ),
        migrations.AddField(
            model_name='kvmodel',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kvmodel',
            name='key',
            field=models.CharField(blank=True, max_length=500, unique=True, verbose_name='key'),
        ),
    ]
