# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-20 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0012_auto_20190320_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvmodel',
            name='update',
        ),
    ]
