# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-07 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0013_remove_kvmodel_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvmodel',
            name='key',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='详细'),
        ),
    ]
