# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-08 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0013_auto_20170426_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='KVModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=500, verbose_name='key')),
                ('value', models.TextField(blank=True, verbose_name='value')),
            ],
        ),
    ]
