# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-23 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0014_auto_20190407_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvmodel',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
