# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-25 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0015_kvmodel_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmodel',
            name='at',
        ),
        migrations.RemoveField(
            model_name='logmodel',
            name='key',
        ),
        migrations.RemoveField(
            model_name='logmodel',
            name='kind',
        ),
        migrations.AddField(
            model_name='logmodel',
            name='creattime',
            field=models.DateTimeField(auto_now=True, verbose_name='产生时间'),
        ),
        migrations.AddField(
            model_name='logmodel',
            name='operation',
            field=models.CharField(blank=True, max_length=100, verbose_name='操作类型'),
        ),
        migrations.AddField(
            model_name='logmodel',
            name='tag',
            field=models.CharField(blank=True, help_text='用户快速查询', max_length=100, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
