# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0015_auto_20190517_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='详细'),
        ),
    ]
