# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-12-04 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0016_auto_20190525_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitmodel',
            name='group',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
