# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-07 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0016_auto_20170603_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvmodel',
            name='editor_type',
            field=models.CharField(choices=[('blocktext', '\u666e\u901a\u7f16\u8f91\u5668'), ('richetext', '\u5bcc\u6587\u672c\u7f16\u8f91\u5668')], default='blocktext', max_length=30, verbose_name='\u7f16\u8f91\u5668\u7c7b\u578b'),
        ),
    ]
