# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-22 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0016_auto_20190522_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='细节'),
        ),
    ]
