# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-08-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0017_auto_20191204_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitmodel',
            name='desp',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
