# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-30 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0019_auto_20170627_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='\u8be6\u7ec6'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='kind',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u79cd\u7c7b'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='permitmodel',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='\u7528\u6237\u7ec4'),
        ),
        migrations.AlterField(
            model_name='permitmodel',
            name='permit',
            field=models.TextField(default='{}', verbose_name='\u7528\u6237\u6743\u9650'),
        ),
    ]
