# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-21 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0021_permitmodel_desp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u6743\u9650\u7ec4\u540d\u79f0')),
                ('desp', models.TextField(blank=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.RemoveField(
            model_name='permitmodel',
            name='group',
        ),
        migrations.AddField(
            model_name='permitgroup',
            name='permit',
            field=models.ManyToManyField(to='director.PermitModel', verbose_name='\u6743\u9650'),
        ),
    ]
