# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-21 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('director', '0022_auto_20170921_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitgroup',
            name='permit',
        ),
        migrations.AddField(
            model_name='permitmodel',
            name='group',
            field=models.ManyToManyField(to='auth.Group', verbose_name='\u7528\u6237\u7ec4'),
        ),
        migrations.DeleteModel(
            name='PermitGroup',
        ),
    ]
