# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-21 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0023_auto_20170921_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitmodel',
            name='name',
            field=models.CharField(default='kong', max_length=300, verbose_name='\u6743\u9650\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
