# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-21 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.base.jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0024_permitmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitmodel',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='\u7528\u6237\u7ec4'),
        ),
        migrations.AlterField(
            model_name='permitmodel',
            name='permit',
            field=helpers.base.jsonfield.JsonField(default={}, verbose_name='\u7528\u6237\u6743\u9650'),
        ),
    ]
