# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-04 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.base.jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0025_auto_20170921_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='kind',
            field=models.CharField(blank=True, max_length=100, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='permitmodel',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='user group'),
        ),
        migrations.AlterField(
            model_name='permitmodel',
            name='permit',
            field=helpers.base.jsonfield.JsonField(default={}, verbose_name='user permit'),
        ),
    ]
