# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-30 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0027_auto_20171218_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvmodel',
            name='desp',
            field=models.TextField(blank=True, verbose_name='\u63cf\u8ff0'),
        ),
    ]
