# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('addr', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('id_code', models.CharField(blank=True, max_length=30, verbose_name='身份证号码')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='ValidatorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='验证码')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
