# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-07-13 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('authuser', '0001_initial'), ('authuser', '0002_auto_20180922_2246'), ('authuser', '0003_userinfo_user'), ('authuser', '0004_userinfo_nickname'), ('authuser', '0005_userinfo_head'), ('authuser', '0006_auto_20180924_0055'), ('authuser', '0007_auto_20180927_2359'), ('authuser', '0008_auto_20181013_0106'), ('authuser', '0009_loggedinuser')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='验证码')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='手机号')),
                ('code', models.CharField(max_length=30, verbose_name='验证码')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
