# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-12-26 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authuser', '0001_initial_squashed_0009_loggedinuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.DateTimeField(blank=True, null=True, verbose_name='上次修改时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
