# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_userinfo_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='head',
            field=models.CharField(blank=True, max_length=300, verbose_name='头像'),
        ),
    ]
